name: Build PAF Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build libpaf.so
        run: |
          make
          mkdir -p dist/linux
          cp libpaf/libpaf.so dist/linux/ || true

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build libpaf.dll
        shell: cmd
        run: |
          if exist Makefile (
            make
            if not exist dist\windows mkdir dist\windows
            copy libpaf\libpaf.dll dist\windows\
          )

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build libpaf.dylib
        run: |
          make
          mkdir -p dist/macos
          cp libpaf/libpaf.dylib dist/macos/ || true
